Search.appendIndex(
    [
                {
            "fqsen": "\\ThinkingData\\SDK_VERSION",
            "name": "SDK_VERSION",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_SDK_VERSION"
        },                {
            "fqsen": "\\ThinkingData\\SDK_LIB_NAME",
            "name": "SDK_LIB_NAME",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_SDK_LIB_NAME"
        },                {
            "fqsen": "\\ThinkingData\\TRACK_TYPE_NORMAL",
            "name": "TRACK_TYPE_NORMAL",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_TRACK_TYPE_NORMAL"
        },                {
            "fqsen": "\\ThinkingData\\TRACK_TYPE_FIRST",
            "name": "TRACK_TYPE_FIRST",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_TRACK_TYPE_FIRST"
        },                {
            "fqsen": "\\ThinkingData\\TRACK_TYPE_UPDATE",
            "name": "TRACK_TYPE_UPDATE",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_TRACK_TYPE_UPDATE"
        },                {
            "fqsen": "\\ThinkingData\\TRACK_TYPE_OVERWRITE",
            "name": "TRACK_TYPE_OVERWRITE",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_TRACK_TYPE_OVERWRITE"
        },                {
            "fqsen": "\\ThinkingData\\USER_TYPE_SET",
            "name": "USER_TYPE_SET",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_USER_TYPE_SET"
        },                {
            "fqsen": "\\ThinkingData\\USER_TYPE_SET_ONCE",
            "name": "USER_TYPE_SET_ONCE",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_USER_TYPE_SET_ONCE"
        },                {
            "fqsen": "\\ThinkingData\\USER_TYPE_UNSET",
            "name": "USER_TYPE_UNSET",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_USER_TYPE_UNSET"
        },                {
            "fqsen": "\\ThinkingData\\USER_TYPE_APPEND",
            "name": "USER_TYPE_APPEND",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_USER_TYPE_APPEND"
        },                {
            "fqsen": "\\ThinkingData\\USER_TYPE_UNIQUE_APPEND",
            "name": "USER_TYPE_UNIQUE_APPEND",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_USER_TYPE_UNIQUE_APPEND"
        },                {
            "fqsen": "\\ThinkingData\\USER_TYPE_ADD",
            "name": "USER_TYPE_ADD",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_USER_TYPE_ADD"
        },                {
            "fqsen": "\\ThinkingData\\USER_TYPE_DEL",
            "name": "USER_TYPE_DEL",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_USER_TYPE_DEL"
        },                {
            "fqsen": "\\ThinkingData\\NAME_PATTERN",
            "name": "NAME_PATTERN",
            "summary": "",
            "url": "namespaces/thinkingdata.html#constant_NAME_PATTERN"
        },                {
            "fqsen": "\\ThinkingData\\ThinkingDataException",
            "name": "ThinkingDataException",
            "summary": "Exception",
            "url": "classes/ThinkingData-ThinkingDataException.html"
        },                {
            "fqsen": "\\ThinkingData\\ThinkingDataNetWorkException",
            "name": "ThinkingDataNetWorkException",
            "summary": "Network\u0020exception",
            "url": "classes/ThinkingData-ThinkingDataNetWorkException.html"
        },                {
            "fqsen": "\\ThinkingData\\ThinkingDataAnalytics",
            "name": "ThinkingDataAnalytics",
            "summary": "\u005BDeprecated\u0020class\u005D",
            "url": "classes/ThinkingData-ThinkingDataAnalytics.html"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics",
            "name": "TDAnalytics",
            "summary": "Entry\u0020of\u0020SDK",
            "url": "classes/ThinkingData-TDAnalytics.html"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Construct",
            "url": "classes/ThinkingData-TDAnalytics.html#method___construct"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Auser_set\u0028\u0029",
            "name": "user_set",
            "summary": "Set\u0020user\u0020properties.\u0020would\u0020overwrite\u0020existing\u0020names",
            "url": "classes/ThinkingData-TDAnalytics.html#method_user_set"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Auser_setOnce\u0028\u0029",
            "name": "user_setOnce",
            "summary": "Set\u0020user\u0020properties,\u0020If\u0020such\u0020property\u0020had\u0020been\u0020set\u0020before,\u0020this\u0020message\u0020would\u0020be\u0020neglected.",
            "url": "classes/ThinkingData-TDAnalytics.html#method_user_setOnce"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Auser_add\u0028\u0029",
            "name": "user_add",
            "summary": "To\u0020accumulate\u0020operations\u0020against\u0020the\u0020property",
            "url": "classes/ThinkingData-TDAnalytics.html#method_user_add"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Auser_append\u0028\u0029",
            "name": "user_append",
            "summary": "To\u0020add\u0020user\u0020properties\u0020of\u0020array\u0020type",
            "url": "classes/ThinkingData-TDAnalytics.html#method_user_append"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Auser_uniq_append\u0028\u0029",
            "name": "user_uniq_append",
            "summary": "Append\u0020user\u0020properties\u0020to\u0020array\u0020type\u0020by\u0020unique.",
            "url": "classes/ThinkingData-TDAnalytics.html#method_user_uniq_append"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Auser_unset\u0028\u0029",
            "name": "user_unset",
            "summary": "Clear\u0020the\u0020user\u0020properties\u0020of\u0020users",
            "url": "classes/ThinkingData-TDAnalytics.html#method_user_unset"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Auser_del\u0028\u0029",
            "name": "user_del",
            "summary": "Delete\u0020a\u0020user,\u0020This\u0020operation\u0020cannot\u0020be\u0020undone",
            "url": "classes/ThinkingData-TDAnalytics.html#method_user_del"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Atrack\u0028\u0029",
            "name": "track",
            "summary": "Report\u0020ordinary\u0020event",
            "url": "classes/ThinkingData-TDAnalytics.html#method_track"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Atrack_first\u0028\u0029",
            "name": "track_first",
            "summary": "Report\u0020first\u0020event.",
            "url": "classes/ThinkingData-TDAnalytics.html#method_track_first"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Atrack_update\u0028\u0029",
            "name": "track_update",
            "summary": "Report\u0020updatable\u0020event",
            "url": "classes/ThinkingData-TDAnalytics.html#method_track_update"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Atrack_overwrite\u0028\u0029",
            "name": "track_overwrite",
            "summary": "Report\u0020overwrite\u0020event.",
            "url": "classes/ThinkingData-TDAnalytics.html#method_track_overwrite"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003AcheckEventName\u0028\u0029",
            "name": "checkEventName",
            "summary": "Check\u0020event\u0020name",
            "url": "classes/ThinkingData-TDAnalytics.html#method_checkEventName"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003AcheckEventId\u0028\u0029",
            "name": "checkEventId",
            "summary": "Check\u0020event\u0020id",
            "url": "classes/ThinkingData-TDAnalytics.html#method_checkEventId"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003AcheckAccountIdAndDistinctId\u0028\u0029",
            "name": "checkAccountIdAndDistinctId",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_checkAccountIdAndDistinctId"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_add"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003AassertProperties\u0028\u0029",
            "name": "assertProperties",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_assertProperties"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003AgetDatetime\u0028\u0029",
            "name": "getDatetime",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_getDatetime"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003AgetFormatDate\u0028\u0029",
            "name": "getFormatDate",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_getFormatDate"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003AextractUserTime\u0028\u0029",
            "name": "extractUserTime",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_extractUserTime"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003AextractStringProperty\u0028\u0029",
            "name": "extractStringProperty",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_extractStringProperty"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Auuid\u0028\u0029",
            "name": "uuid",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_uuid"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Aclear_public_properties\u0028\u0029",
            "name": "clear_public_properties",
            "summary": "clear\u0020common\u0020properties",
            "url": "classes/ThinkingData-TDAnalytics.html#method_clear_public_properties"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Aregister_public_properties\u0028\u0029",
            "name": "register_public_properties",
            "summary": "set\u0020common\u0020properties",
            "url": "classes/ThinkingData-TDAnalytics.html#method_register_public_properties"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Amerge_public_properties\u0028\u0029",
            "name": "merge_public_properties",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_merge_public_properties"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Aregister_dynamic_public_properties\u0028\u0029",
            "name": "register_dynamic_public_properties",
            "summary": "set\u0020dynamic\u0020common\u0020properties",
            "url": "classes/ThinkingData-TDAnalytics.html#method_register_dynamic_public_properties"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Amerge_dynamic_public_properties\u0028\u0029",
            "name": "merge_dynamic_public_properties",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_merge_dynamic_public_properties"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Aflush\u0028\u0029",
            "name": "flush",
            "summary": "report\u0020data\u0020immediately",
            "url": "classes/ThinkingData-TDAnalytics.html#method_flush"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "close\u0020and\u0020exit\u0020sdk",
            "url": "classes/ThinkingData-TDAnalytics.html#method_close"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003AisStrict\u0028\u0029",
            "name": "isStrict",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#method_isStrict"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003A\u0024consumer",
            "name": "consumer",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#property_consumer"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003A\u0024publicProperties",
            "name": "publicProperties",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#property_publicProperties"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003A\u0024dynamicPublicPropertiesCallback",
            "name": "dynamicPublicPropertiesCallback",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#property_dynamicPublicPropertiesCallback"
        },                {
            "fqsen": "\\ThinkingData\\TDAnalytics\u003A\u003A\u0024enableUUID",
            "name": "enableUUID",
            "summary": "",
            "url": "classes/ThinkingData-TDAnalytics.html#property_enableUUID"
        },                {
            "fqsen": "\\ThinkingData\\TDAbstractConsumer",
            "name": "TDAbstractConsumer",
            "summary": "Abstract\u0020consumer",
            "url": "classes/ThinkingData-TDAbstractConsumer.html"
        },                {
            "fqsen": "\\ThinkingData\\TDAbstractConsumer\u003A\u003AgetStrictStatus\u0028\u0029",
            "name": "getStrictStatus",
            "summary": "Get\u0020strict\u0020status",
            "url": "classes/ThinkingData-TDAbstractConsumer.html#method_getStrictStatus"
        },                {
            "fqsen": "\\ThinkingData\\TDAbstractConsumer\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "report\u0020data",
            "url": "classes/ThinkingData-TDAbstractConsumer.html#method_send"
        },                {
            "fqsen": "\\ThinkingData\\TDAbstractConsumer\u003A\u003Aflush\u0028\u0029",
            "name": "flush",
            "summary": "report\u0020data\u0020immediately",
            "url": "classes/ThinkingData-TDAbstractConsumer.html#method_flush"
        },                {
            "fqsen": "\\ThinkingData\\TDAbstractConsumer\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "close\u0020and\u0020release\u0020resource",
            "url": "classes/ThinkingData-TDAbstractConsumer.html#method_close"
        },                {
            "fqsen": "\\ThinkingData\\TDAbstractConsumer\u003A\u003A\u0024strict",
            "name": "strict",
            "summary": "",
            "url": "classes/ThinkingData-TDAbstractConsumer.html#property_strict"
        },                {
            "fqsen": "\\ThinkingData\\FileConsumer",
            "name": "FileConsumer",
            "summary": "\u005BDeprecated\u0020class\u005D",
            "url": "classes/ThinkingData-FileConsumer.html"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer",
            "name": "TDFileConsumer",
            "summary": "Write\u0020data\u0020to\u0020file,\u0020it\u0020works\u0020with\u0020LogBus.\u0020not\u0020support\u0020multiple\u0020thread",
            "url": "classes/ThinkingData-TDFileConsumer.html"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "init\u0020FileConsumer",
            "url": "classes/ThinkingData-TDFileConsumer.html#method___construct"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "write\u0020data",
            "url": "classes/ThinkingData-TDFileConsumer.html#method_send"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003Aflush\u0028\u0029",
            "name": "flush",
            "summary": "report\u0020data\u0020immediately",
            "url": "classes/ThinkingData-TDFileConsumer.html#method_flush"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "close\u0020and\u0020release\u0020resource",
            "url": "classes/ThinkingData-TDFileConsumer.html#method_close"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003AgetFileName\u0028\u0029",
            "name": "getFileName",
            "summary": "",
            "url": "classes/ThinkingData-TDFileConsumer.html#method_getFileName"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003AfileSizeOut\u0028\u0029",
            "name": "fileSizeOut",
            "summary": "",
            "url": "classes/ThinkingData-TDFileConsumer.html#method_fileSizeOut"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003A\u0024fileHandler",
            "name": "fileHandler",
            "summary": "",
            "url": "classes/ThinkingData-TDFileConsumer.html#property_fileHandler"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003A\u0024fileName",
            "name": "fileName",
            "summary": "",
            "url": "classes/ThinkingData-TDFileConsumer.html#property_fileName"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003A\u0024fileDirectory",
            "name": "fileDirectory",
            "summary": "",
            "url": "classes/ThinkingData-TDFileConsumer.html#property_fileDirectory"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003A\u0024filePrefix",
            "name": "filePrefix",
            "summary": "",
            "url": "classes/ThinkingData-TDFileConsumer.html#property_filePrefix"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003A\u0024fileSize",
            "name": "fileSize",
            "summary": "",
            "url": "classes/ThinkingData-TDFileConsumer.html#property_fileSize"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003A\u0024rotateHourly",
            "name": "rotateHourly",
            "summary": "",
            "url": "classes/ThinkingData-TDFileConsumer.html#property_rotateHourly"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003A\u0024buffers",
            "name": "buffers",
            "summary": "",
            "url": "classes/ThinkingData-TDFileConsumer.html#property_buffers"
        },                {
            "fqsen": "\\ThinkingData\\TDFileConsumer\u003A\u003A\u0024bufferSize",
            "name": "bufferSize",
            "summary": "",
            "url": "classes/ThinkingData-TDFileConsumer.html#property_bufferSize"
        },                {
            "fqsen": "\\ThinkingData\\BatchConsumer",
            "name": "BatchConsumer",
            "summary": "\u005BDeprecated\u0020class\u005D",
            "url": "classes/ThinkingData-BatchConsumer.html"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer",
            "name": "TDBatchConsumer",
            "summary": "upload\u0020data\u0020to\u0020TE\u0020by\u0020http.\u0020not\u0020support\u0020multiple\u0020thread",
            "url": "classes/ThinkingData-TDBatchConsumer.html"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "init\u0020BatchConsumer",
            "url": "classes/ThinkingData-TDBatchConsumer.html#method___construct"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#method___destruct"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "report\u0020data",
            "url": "classes/ThinkingData-TDBatchConsumer.html#method_send"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003Aflush\u0028\u0029",
            "name": "flush",
            "summary": "Flush\u0020data",
            "url": "classes/ThinkingData-TDBatchConsumer.html#method_flush"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Close\u0020consumer",
            "url": "classes/ThinkingData-TDBatchConsumer.html#method_close"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003AsetCompress\u0028\u0029",
            "name": "setCompress",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#method_setCompress"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003AsetFlushSize\u0028\u0029",
            "name": "setFlushSize",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#method_setFlushSize"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003AopenThrowException\u0028\u0029",
            "name": "openThrowException",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#method_openThrowException"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003AdoRequest\u0028\u0029",
            "name": "doRequest",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#method_doRequest"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#property_url"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A\u0024appid",
            "name": "appid",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#property_appid"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A\u0024buffers",
            "name": "buffers",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#property_buffers"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A\u0024maxSize",
            "name": "maxSize",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#property_maxSize"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A\u0024requestTimeout",
            "name": "requestTimeout",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#property_requestTimeout"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A\u0024compress",
            "name": "compress",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#property_compress"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A\u0024retryTimes",
            "name": "retryTimes",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#property_retryTimes"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A\u0024isThrowException",
            "name": "isThrowException",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#property_isThrowException"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A\u0024cacheBuffers",
            "name": "cacheBuffers",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#property_cacheBuffers"
        },                {
            "fqsen": "\\ThinkingData\\TDBatchConsumer\u003A\u003A\u0024cacheCapacity",
            "name": "cacheCapacity",
            "summary": "",
            "url": "classes/ThinkingData-TDBatchConsumer.html#property_cacheCapacity"
        },                {
            "fqsen": "\\ThinkingData\\DebugConsumer",
            "name": "DebugConsumer",
            "summary": "\u005BDeprecated\u0020class\u005D",
            "url": "classes/ThinkingData-DebugConsumer.html"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer",
            "name": "TDDebugConsumer",
            "summary": "The\u0020data\u0020is\u0020reported\u0020one\u0020by\u0020one,\u0020and\u0020when\u0020an\u0020error\u0020occurs,\u0020the\u0020exception\u0020will\u0020be\u0020thrown",
            "url": "classes/ThinkingData-TDDebugConsumer.html"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "init\u0020DebugConsumer",
            "url": "classes/ThinkingData-TDDebugConsumer.html#method___construct"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "report\u0020data",
            "url": "classes/ThinkingData-TDDebugConsumer.html#method_send"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer\u003A\u003AsetDebugOnly\u0028\u0029",
            "name": "setDebugOnly",
            "summary": "",
            "url": "classes/ThinkingData-TDDebugConsumer.html#method_setDebugOnly"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "close\u0020and\u0020release\u0020resource",
            "url": "classes/ThinkingData-TDDebugConsumer.html#method_close"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer\u003A\u003AdoRequest\u0028\u0029",
            "name": "doRequest",
            "summary": "",
            "url": "classes/ThinkingData-TDDebugConsumer.html#method_doRequest"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer\u003A\u003A\u0024url",
            "name": "url",
            "summary": "",
            "url": "classes/ThinkingData-TDDebugConsumer.html#property_url"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer\u003A\u003A\u0024appid",
            "name": "appid",
            "summary": "",
            "url": "classes/ThinkingData-TDDebugConsumer.html#property_appid"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer\u003A\u003A\u0024requestTimeout",
            "name": "requestTimeout",
            "summary": "",
            "url": "classes/ThinkingData-TDDebugConsumer.html#property_requestTimeout"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer\u003A\u003A\u0024writerData",
            "name": "writerData",
            "summary": "",
            "url": "classes/ThinkingData-TDDebugConsumer.html#property_writerData"
        },                {
            "fqsen": "\\ThinkingData\\TDDebugConsumer\u003A\u003A\u0024deviceId",
            "name": "deviceId",
            "summary": "",
            "url": "classes/ThinkingData-TDDebugConsumer.html#property_deviceId"
        },                {
            "fqsen": "\\ThinkingData\\TALogger",
            "name": "TALogger",
            "summary": "\u005BDeprecated\u0020class\u005D",
            "url": "classes/ThinkingData-TALogger.html"
        },                {
            "fqsen": "\\ThinkingData\\TDLog",
            "name": "TDLog",
            "summary": "Log\u0020module",
            "url": "classes/ThinkingData-TDLog.html"
        },                {
            "fqsen": "\\ThinkingData\\TDLog\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "",
            "url": "classes/ThinkingData-TDLog.html#method_log"
        },                {
            "fqsen": "\\ThinkingData\\TDLog\u003A\u003A\u0024enable",
            "name": "enable",
            "summary": "",
            "url": "classes/ThinkingData-TDLog.html#property_enable"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\ThinkingData",
            "name": "ThinkingData",
            "summary": "",
            "url": "namespaces/thinkingdata.html"
        }            ]
);
